version: '2.4'
services:
  db:
    image: mysql
    container_name: user-service
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - user-service_data:/var/lib/mysql
volumes:
  user-service_data:
